//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VK.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Вы пишите код? Вы рисуете? Играете?
Тогда почему бы не включить прекрасную музыку на фон?

Ограничения на кол-во постов - не более 100. Это ограничение VK.

Музыка скачивается в папку Music.
Она находится в той же директории, что и программа.


Как запускать с параметром?
Макет: ""Путь до программы"" ""Айди группы с -"" ""Кол-во постов загружать (Не более 100)""
Пример: ""D:\VK\R1.exe"" -74779558 80
Вы можете создать ярлык к программе и в его свойствах, после пути к файлу и дописать id группы кол-во постов.
Если вы указали id, обязательно нужно указывать, какое кол-во постов загружать.

Нашли баг? Пиши автору.

Автор: vk.com/id208497682

Обновление искать на github.com/egor2998067/Perception-of-music

Для работы программы у Вас должен быть установлен windows media player.")]
        public string ND {
            get {
                return ((string)(this["ND"]));
            }
            set {
                this["ND"] = value;
            }
        }
    }
}
